name: Bump version on push

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          # Prerequisite: You have a deploy key in your repo with 'Write Access'.
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Configure Git
        run: |
          # Configure name/email for commits so we can identify these commits.
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Stop if last commit is from GitHub Actions (avoid infinite loop)
        id: check_who_commits
        run: |
          # Get the email address of the last commit
          LAST_COMMIT_AUTHOR_EMAIL="$(git log -1 --pretty=format:'%ae')"
          echo "Last commit author email: $LAST_COMMIT_AUTHOR_EMAIL"
          # If this email == GitHub Actions? Then abort
          if [ "$LAST_COMMIT_AUTHOR_EMAIL" = "41898282+github-actions[bot]@users.noreply.github.com" ]; then
            echo "Commit was made by GitHub Action, skipping..."
            echo "::set-output name=skip::true"
            exit 0
          else
            echo "Commit was made by $LAST_COMMIT_AUTHOR_EMAIL ..."
            echo "::set-output name=skip::false"
          fi

      - name: Get current version
        id: get_version
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi
          # Try to find the line that starts with '## v', e.g. "## v1.2.3 - 2025-01-21"
          CURRENT_VERSION="$(grep -m1 '^## v' VERSIONS.md | sed -E 's/^## v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')"
          
          if [ -z "$CURRENT_VERSION" ]; then
            echo "No version found in VERSIONS.md - default=0.0.0"
            CURRENT_VERSION="0.0.0"
          fi
          
          echo "Current version: $CURRENT_VERSION"
          echo "::set-output name=current_version::$CURRENT_VERSION"

      - name: Determine new version
        id: determine_new_version
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi
        
          # If HEAD~1 exists (i.e., there is at least one previous commit):
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            # Commit messages since the last commit
            COMMITS="$(git log --pretty=format:%B HEAD~1..HEAD)"
          else
            # If only one commit
            COMMITS="$(git log --pretty=format:%B HEAD)"
          fi
          
          echo "Commit Messages:"
          echo "$COMMITS"
      
          CURRENT_VERSION="${{ steps.get_version.outputs.current_version }}"
          
          # Split MAJOR.MINOR.PATCH
          MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
          MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
          PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3)
      
          # Look for a special tag <major_release></major_release> in the commit text
          if echo "$COMMITS" | grep -q "<major_release></major_release>"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            RELEASE_TYPE="(MAJOR)"
          else
            PATCH=$((PATCH + 1))
            RELEASE_TYPE="(PATCH)"
          fi
      
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION $RELEASE_TYPE"
          echo "::set-output name=new_version::$NEW_VERSION"
          
          # Release notes are simply the commit messages
          echo "::set-output name=release_notes::$COMMITS"

      - name: Update VERSIONS.md with new version
        id: update_versions_md
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi
        
          NEW_VERSION="${{ steps.determine_new_version.outputs.new_version }}"
          RELEASE_NOTES="${{ steps.determine_new_version.outputs.release_notes }}"

          # Generate an ISO8601 UTC timestamp (e.g., 2025-01-23T18:20:02.123Z)
          DATE="$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')"
          # Date 
          echo "::set-output name=new_date::$DATE"
          
          # Write a new section at the beginning of VERSIONS.md
          {
            echo "## v${NEW_VERSION} - ${DATE}"
            echo ""
            while IFS= read -r line; do
              echo "- $line"
            done <<< "$RELEASE_NOTES"
            echo ""
          } > NEW_VERSIONS.md

          cat VERSIONS.md >> NEW_VERSIONS.md
          mv NEW_VERSIONS.md VERSIONS.md

      - name: (Optional) Update README.md
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi
        
          NEW_VERSION="${{ steps.determine_new_version.outputs.new_version }}"
          # Replace line "## Version 0.0.1" with e.g. "## Version 1.2.3"
          sed -i "s|^## Version .*|## Version ${NEW_VERSION}|" README.md
          DATE="${{ steps.update_versions_md.outputs.new_date }}"
          # Replace line "**Date:** 2024-12-17" with e.g. "**Date:** 2025-01-23T18:20:02.123Z"
          sed -i "s|^- \*\*Date:\*\* .*|- **Date:** ${DATE}|" README.md         
          echo "README.md (if placeholders present) updated."

      - name: Commit changes
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi
        
          NEW_VERSION="${{ steps.determine_new_version.outputs.new_version }}"
          git add .
          git commit -m "chore: bump version to ${NEW_VERSION}"

      - name: Push changes
        run: |
          if [ "${{ steps.check_who_commits.outputs.skip }}" == "true" ]; then
            echo "Is a rebumping, skip ..."
            exit 0
          fi

          # Push to main (or another branch if applicable)
          git push origin main
